Check point 1
eTimokhov/phoneshop pull request #1
Opened 2019-06-03 15:59 UTC by eTimokhov

2019-06-04 11:42 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            "SELECT * FROM phone2color " +
а почему выборка не из colors таблицы, а из many to many?

2019-06-04 11:42 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            Phone phone = jdbcTemplate.queryForObject(FIND_PHONE_BY_ID, new BeanPropertyRowMapper<>(Phone.class), key);
mapper можно вынести как бин, т.к синглтон

2019-06-04 11:42 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        if (phone == null) {
можно через Objects.requireNonNull

2019-06-04 11:42 UTC, OEAndreiIvanov commented on core/src/test/resources/context/JdbcPhoneDaoTest-context.xml
> +    <bean id="dataSource" class="org.springframework.jdbc.datasource.DriverManagerDataSource">
попробуй переиспользовать бины из core, но поставить другие проперти для dataSource

2019-06-04 11:42 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        Long phoneId = insertPhone.executeAndReturnKey(parameters).longValue();
а если уже есть такой телефон?

2019-06-04 11:52 UTC, eTimokhov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        Long phoneId = insertPhone.executeAndReturnKey(parameters).longValue();
а можно его просто удалять и добавлять заново? или надо делать через UPDATE?

2019-06-04 21:12 UTC, eTimokhov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        Long phoneId = insertPhone.executeAndReturnKey(parameters).longValue();
мне пришлось для обновления телефона вручную в sql-запросе прописывать все столбцы таблицы. может можно было сделать это лучше?

2019-06-05 12:29 UTC, OEAndreiIvanov requested changes

2019-06-05 12:29 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +            return;
красивей if/else написать

2019-06-05 12:29 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        Long phoneId = insertPhone.executeAndReturnKey(parameters).longValue();
не припомню, можно оставить так

2019-06-05 12:29 UTC, OEAndreiIvanov commented on core/src/test/resources/conf/JdbcPhoneDaoTest-application.properties
> +db.driver=org.h2.Driver
зачем так называть - это же в целом для тест контекста проперти

2019-06-05 12:29 UTC, OEAndreiIvanov commented on core/src/test/resources/context/JdbcPhoneDaoTest-context.xml
> +    <jdbc:initialize-database enabled="${db.insertSchema}" data-source="dataSource">
это нужно оставлять?

2019-06-05 12:29 UTC, OEAndreiIvanov commented on core/src/test/resources/context/JdbcPhoneDaoTest-context.xml
> +<?xml version="1.0" encoding="UTF-8"?>
тоже назвал бы чем то вроде test-context

2019-06-05 19:36 UTC, eTimokhov commented on core/src/test/resources/conf/JdbcPhoneDaoTest-application.properties
> +db.driver=org.h2.Driver
думал, что могут понадобиться разные контексты и проперти для разных тестов

2019-06-06 09:25 UTC, OEAndreiIvanov commented on core/src/test/resources/context/test-context.xml
> +    <context:component-scan base-package="com.es.core"/>
хотелось бы, чтобы тест контекст накатывался сверху обычного, только как необходимые изменения для интегрейшен тестов
попробуй сделать свою аннотацию, типо @IntegrationTest, в которой есть нужные конфиги итд + важная spring аннотация для тестов базы, которую я не увидел

2019-06-07 09:07 UTC, OEAndreiIvanov requested changes

2019-06-07 09:07 UTC, OEAndreiIvanov commented on core/src/test/java/com/es/core/model/phone/JdbcPhoneDaoTest.java
> +@RunWith(SpringJUnit4ClassRunner.class)
тоже можно вынести в аннотацию

2019-06-07 09:07 UTC, OEAndreiIvanov commented on core/src/test/resources/context/test-context.xml
> +    <bean id="transactionManager" class="org.springframework.jdbc.datasource.DataSourceTransactionManager">
а почему нужен отдельный для тестов?

2019-06-07 09:07 UTC, OEAndreiIvanov commented on core/src/test/resources/context/test-context.xml
> +    <import resource="applicationContext-core.xml" />
я бы лучше в аннотации два прописал, и убрал отсюда зависимость

2019-06-07 11:02 UTC, OEAndreiIvanov approved these changes

2019-06-07 11:04 UTC, merged