Check point 2
eTimokhov/phoneshop pull request #2
Opened 2020-01-28 12:18 UTC by eTimokhov

2020-01-28 13:03 UTC, OEAndreiIvanov requested changes

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        Stock stock = stockDao.getStock(phoneId);
а здесь почему не опшионал возвращается?

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        if (stock.getStock() - stock.getReserved() < quantity) {
что если понадобится в другом месте схожая проверка? например перед сабмитом ордера

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        stock.setReserved(stock.getReserved() + quantity);
и тут

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        if (optionalCartItem.isPresent()) {
продолжай в той же цепочке, старайся использовать опшионал без ispresent/isempty чеков

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            cartItem.setQuantity(cartItem.getQuantity() + quantity);
мб стоит add or update сделать, с возможной нулевой итоговой qty

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        for (Map.Entry<Long, Long> entry : items.entrySet()) {
и как то объединить с предыдущим

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        cart.getCartItems().removeIf(ci -> ci.getPhone().getId().equals(phoneId));
кстати предикат по поиску телефона тоже можно вынести

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        BigDecimal totalPrice = cart.getCartItems().stream()
а shipping? вынеси в отдельный сервис

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +    private static final String FIND_COLORS_BY_PHONE_ID =
константы в самом начале идут

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        sqlQuery.append(ascending ? " ASC " : " DESC ");
енам используй

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        if (searchTerms != null && !searchTerms.trim().isEmpty()) {
StringUtils

2020-01-28 13:03 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/stock/JdbcStockDao.java
> +            throw new IllegalArgumentException("Phone with id " + phoneId + " not found.");
это где то всегда хэндлается?

2020-01-28 13:03 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +        if (bindingResult.hasErrors()) {
многовато валидации для контроллера
к тому же, для ajax имеет смысл просто кидать эксепшены, мапить в fe friendly формат и отлавливать на fe

2020-01-28 13:03 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +        List<Phone> phones = phoneDao.findAll(searchTerms, orderBy, ascending, (page - 1) * RESULTS_PER_PAGE, RESULTS_PER_PAGE);
findAll -> findPage, дао это не уровень контроллера, мб сразу возвращать pagination data со всем необходимым для фронта

2020-01-31 10:28 UTC, eTimokhov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        if (optionalCartItem.isPresent()) {
не знаю как это сделать без метода ifPresentOrElse, а он доступен только в java 9

2020-01-31 10:28 UTC, eTimokhov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        sqlQuery.append(ascending ? " ASC " : " DESC ");
не особо понимаю, зачем

2020-01-31 11:09 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        if (optionalCartItem.isPresent()) {
ну ок
сделай тогда два метода - addToCart и updateCartItem

2020-01-31 11:10 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        sqlQuery.append(ascending ? " ASC " : " DESC ");
у сортировки два варианта направления - выглядит более естественно чем булеан

2020-02-05 09:54 UTC, OEAndreiIvanov requested changes

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/CartCalculationServiceImpl.java
> +public class CartCalculationServiceImpl implements CartCalculationService {
а delivery price?

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    public Long getTotalCount() {
непонятное название

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +                e.printStackTrace();
гыгы
логгинг добавь

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +                e.printStackTrace();
и как в этом случае фе узнает про out of stock?

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    private void addOrUpdate(Long phoneId, Long quantity, boolean addQuantity) throws ItemNotFoundException, OutOfStockException {
можно просто передавать отрицательный quantity

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        stockManager.changeReservedBy(stock, quantityDifference);
а резервацию стока вообще нужно было делать? довольно сложная штука

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/ItemNotFoundException.java
> +public class ItemNotFoundException extends Exception {
1. предпочитай runtime exceptions в подобных случаях, меньше мороки
2. можно кидать стандартные эксепшены вроде illegal argument

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/stock/StockManager.java
> +public class StockManager {
до этого у тебя в основном service )

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/stock/StockManager.java
> +    public void changeReservedBy(Stock stock, Long quantity) {
и если уж на то пошло, апдейт стока в забе должен быть тут же

2020-02-05 09:54 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +        PaginationData paginationData = productListPageService.getPaginationData(searchTerms, RESULTS_PER_PAGE);
я думал что и телефоны и инфа о страницах будут в pagination data - так же проще

2020-02-05 09:54 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +        return new GetCartInfoResponse(cartService.getTotalCount(), cartService.getCart().getTotalPrice());
а почему бы просто не отдавать карту? ну или перемаппить её типа CartDto, и пусть фе разбирается

2020-02-05 09:54 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +            return new AddToCartResponse(false, request.getPhoneId(), errorMessage);
можно просто кидать эксепшен, чтобы была 400 и эррор для фе

2020-02-05 09:54 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/phone/JdbcPhoneDao.java
> +        sqlQuery.append(sortingDirection == SortingDirection.DESCENDING ? " DESC " : " ASC ");
можно в енаме прописать ASC и DESC и тут просто их добавлять

2020-02-16 11:09 UTC, eTimokhov commented on core/src/main/java/com/es/core/cart/CartCalculationServiceImpl.java
> +public class CartCalculationServiceImpl implements CartCalculationService {
Это в другом чекпоинте

2020-02-16 11:10 UTC, eTimokhov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +                e.printStackTrace();
я тут хотел сделать корректную обработку ошибок, когда буду делать CartPage, сейчас это что-то вроде заглушки

2020-02-16 11:10 UTC, eTimokhov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        stockManager.changeReservedBy(stock, quantityDifference);
тогда не буду)

2020-02-24 12:35 UTC, OEAndreiIvanov requested changes

2020-02-24 12:35 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    private void addOrUpdate(Long phoneId, Long quantity, boolean addQuantity) throws OutOfStockException {
разве нельзя избавиться от флага, передавать отрицательное в случае чего? такие параметры загрязняют интерфейс

2020-02-24 12:35 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        if (stock.getStock() < newQuantity) {
вынеси в сток сервис то что касается получения стока и его qty, можно реюзать и не усложнять реализацию этого метода

2020-02-24 12:35 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +        cart.getCartItems().removeIf(ci -> ci.getPhone().getId().equals(phone.getId()));
ci -> ci.getPhone().getId().equals(phone.getId()) можно вынести в предикат и переюзать

2020-02-24 12:35 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    }
кстати, собираешься использовать транзакции? в каких местах?

2020-02-24 12:35 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +            String errorMessage = bindingResult.getFieldErrors().stream()
уже лучше, а еще можно вынести в отдельный метод маппинг ошибок, а эксепшены ловить отдельно (почитай как в спринге работать с рест ошибками для контроллеров)

2020-02-24 12:35 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +        return new CartDto(cartService.getCart());
ну, для начала ок, но вообще это конечно должен быть отдельный сервис/фасад, занимающийся маппингом

2020-02-24 12:35 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +    ProductListPageService productListPageService;
название можно попонятнее, хотя бы ProductPageService

2020-02-24 12:35 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/pages/ProductListPageController.java
> +        boolean isSortDirectionValid = Arrays.stream(SortingDirection.values()).anyMatch(value -> value.name().equals(sortDirection.toUpperCase()));
так передавйа сразу енам, пусть спринг маппит и валидирует вместо тебя

2020-02-24 12:47 UTC, eTimokhov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    private void addOrUpdate(Long phoneId, Long quantity, boolean addQuantity) throws OutOfStockException {
тут идея в том, что мы в качестве quantity передаем либо новое значение, либо прибавляем это quantity к старому. по-моему было бы странно, если мы например для удаления айтема будем передавать сюда отрицательное число

2020-02-24 13:46 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    private void addOrUpdate(Long phoneId, Long quantity, boolean addQuantity) throws OutOfStockException {
ок, тогда пусть будет два метода - addToCart(добавляем и мержим если уже сущ) и updateCartItem(апдейт и удаление если передали ноль или qty снизилось до 0)

2020-02-27 12:20 UTC, eTimokhov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    }
думаю в каком-нибудь bulk update карты

2020-02-27 12:20 UTC, eTimokhov commented on web/src/main/java/com/es/phoneshop/web/controller/AjaxCartController.java
> +        return new CartDto(cartService.getCart());
оставлю пока так)

2020-02-27 15:55 UTC, OEAndreiIvanov requested changes

2020-02-27 15:55 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            if (cartItemOpt.isPresent()) {
здесь через опшиооал map orElse можно сделать

2020-02-27 15:55 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +    }
ну так поставь хотя бы на update)

2020-02-27 15:55 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            createCartItem(phoneId, newQuantity);
create ведь здесь не ожидается, а остальное тоже через опшионал

2020-02-27 15:55 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/model/stock/StockService.java
> +    void insert(Stock stock);
такие себе названия для сервиса )

2020-02-27 15:55 UTC, OEAndreiIvanov commented on web/src/main/java/com/es/phoneshop/web/controller/RestExceptionHandler.java
> +        return ResponseEntity.status(HttpStatus.BAD_REQUEST).body("outOfStock");
а логгироввтьья они кстати будут?

2020-02-28 11:06 UTC, eTimokhov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            createCartItem(phoneId, newQuantity);
у нас же может быть ситуация, когда пользователь открыл две вкладки с корзиной, на одной вкладке айтем удалил, а на второй проапдейтил корзину (айтем еще остался). тогда наверное правильно будет его снова добавить в карту и здесь вызовется create

2020-02-28 11:20 UTC, OEAndreiIvanov commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +            createCartItem(phoneId, newQuantity);
это уже lost update получается, я бы кидал эксепшен

2020-02-28 11:23 UTC, merged