Check point 3
eTimokhov/phoneshop pull request #3
Opened 2020-04-06 06:45 UTC by eTimokhov

2020-04-06 14:36 UTC, AndreikaInactive requested changes

2020-04-06 14:36 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/HttpSessionCartService.java
> +                updatePhoneInCart(cartItem.getPhone().getId(), cartItem.getQuantity());
мб просто ловить ошибки в одном месте?

2020-04-06 14:36 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/validator/QuantityValidator.java
> +    public boolean isValid(String s, ConstraintValidatorContext constraintValidatorContext) {
за задумку +, но разве дефолтные min/length аннотации это не покрывают?

2020-04-06 14:36 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/model/phone/PhoneServiceImpl.java
> +    public List<Phone> findAll(String searchTerms, String orderBy, SortingDirection sortingDirection, int offset, int limit) {
это можно перенести в paginationService

2020-04-06 14:36 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        for (int i = 0; i < errors.size(); i++) {
довольно хрупко и не на уровне валидатора

2020-04-06 14:36 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        List<CartItemInfo> cartItemInfos = cartService.getCart().getCartItems().stream()
а в чем преимущество враппера? в любом случае, маппинг нужно делать не на уровне контроллера

2020-04-06 14:36 UTC, AndreikaInactive commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +    private void updateCartItemInfos(@ModelAttribute("cartItemInfos") @Valid CartItemInfoListWrapper cartItemInfos) {
а аннотации зачем?

2020-04-06 15:18 UTC, eTimokhov commented on core/src/main/java/com/es/core/cart/validator/QuantityValidator.java
> +    public boolean isValid(String s, ConstraintValidatorContext constraintValidatorContext) {
они не умеют проверять, что это валидный Long

2020-04-07 13:34 UTC, AndreikaInactive commented on core/src/main/java/com/es/core/cart/validator/QuantityValidator.java
> +    public boolean isValid(String s, ConstraintValidatorContext constraintValidatorContext) {
ну, тогда это не забиндится и вообще не получится? notnull типо

2020-04-09 09:36 UTC, eTimokhov commented on web/src/main/java/com/es/phoneshop/web/controller/pages/CartPageController.java
> +        List<CartItemInfo> cartItemInfos = cartService.getCart().getCartItems().stream()
чтобы на jsp обращаться к списку через поле items враппера:
`                                    <spring:input id="qty-${cartItem.phone.id}" path="items[${status.index}].quantity" type="text"/>
                                    <spring:errors path="items[${status.index}].quantity" cssClass="error"/>`
без него не получится

2020-04-09 14:46 UTC, merged